export const Z_INDEX = {
  BASE: 1,
  MESSAGE_BUBBLE: 1,
  MAIN_LAYOUT: 1,
  MESSAGE_CARD: 2,
  SIDEBAR: 10,
  PANEL: 20,
  OVERLAY: 30,
  SPECIAL_PANEL: 40,
  DIALOG: 50,
  FULLSCREEN: 60,
} as const;
