#!/bin/sh
set -e

STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACMR)
TS_FILES=$(printf "%s\n" "$STAGED_FILES" | grep -E '\.(ts|tsx)$' || true)
FORMAT_FILES=$(printf "%s\n" "$STAGED_FILES" | grep -E '\.(json|md|css)$' || true)

if [ -n "$TS_FILES" ]; then
  printf "%s\n" "$TS_FILES" | xargs npx eslint
fi

if [ -n "$FORMAT_FILES" ]; then
  printf "%s\n" "$FORMAT_FILES" | xargs npx prettier --check
fi
